-- +goose Up
ALTER TABLE instance_settings
    ADD COLUMN IF NOT EXISTS instance_name TEXT NOT NULL DEFAULT 'Dockfin',
    ADD COLUMN IF NOT EXISTS instance_timezone TEXT NOT NULL DEFAULT 'UTC',
    ADD COLUMN IF NOT EXISTS public_ipv4 TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS public_ipv6 TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS do_not_track BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_dns_validation_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS custom_dns_servers TEXT NOT NULL DEFAULT '1.1.1.1',
    ADD COLUMN IF NOT EXISTS is_api_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS allowed_ips TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS webhook_allowed_internal_hosts TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS webhook_allow_localhost BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_mcp_server_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS disable_two_step_confirmation BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_sponsorship_popup_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS is_auto_update_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS auto_update_frequency TEXT NOT NULL DEFAULT '0 0 * * *',
    ADD COLUMN IF NOT EXISTS update_check_frequency TEXT NOT NULL DEFAULT '0 * * * *',
    ADD COLUMN IF NOT EXISTS docker_registry_url TEXT NOT NULL DEFAULT 'ghcr.io',
    ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS smtp_from_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS smtp_from_address TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS smtp_host TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS smtp_port INT NOT NULL DEFAULT 587,
    ADD COLUMN IF NOT EXISTS smtp_encryption TEXT NOT NULL DEFAULT 'starttls',
    ADD COLUMN IF NOT EXISTS smtp_username_enc TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS smtp_password_enc TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS smtp_timeout INT,
    ADD COLUMN IF NOT EXISTS resend_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS resend_api_key_enc TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS oauth_settings (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider            TEXT NOT NULL UNIQUE,
    enabled             BOOLEAN NOT NULL DEFAULT FALSE,
    client_id           TEXT NOT NULL DEFAULT '',
    client_secret_enc   TEXT NOT NULL DEFAULT '',
    redirect_uri        TEXT NOT NULL DEFAULT '',
    tenant              TEXT NOT NULL DEFAULT '',
    base_url            TEXT NOT NULL DEFAULT '',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO oauth_settings (provider) VALUES
    ('github'),
    ('gitlab'),
    ('bitbucket'),
    ('google'),
    ('azure'),
    ('discord'),
    ('authentik'),
    ('clerk'),
    ('infomaniak'),
    ('zitadel')
ON CONFLICT (provider) DO NOTHING;

-- +goose Down
DROP TABLE IF EXISTS oauth_settings;
ALTER TABLE instance_settings
    DROP COLUMN IF EXISTS instance_name,
    DROP COLUMN IF EXISTS instance_timezone,
    DROP COLUMN IF EXISTS public_ipv4,
    DROP COLUMN IF EXISTS public_ipv6,
    DROP COLUMN IF EXISTS do_not_track,
    DROP COLUMN IF EXISTS is_dns_validation_enabled,
    DROP COLUMN IF EXISTS custom_dns_servers,
    DROP COLUMN IF EXISTS is_api_enabled,
    DROP COLUMN IF EXISTS allowed_ips,
    DROP COLUMN IF EXISTS webhook_allowed_internal_hosts,
    DROP COLUMN IF EXISTS webhook_allow_localhost,
    DROP COLUMN IF EXISTS is_mcp_server_enabled,
    DROP COLUMN IF EXISTS disable_two_step_confirmation,
    DROP COLUMN IF EXISTS is_sponsorship_popup_enabled,
    DROP COLUMN IF EXISTS is_auto_update_enabled,
    DROP COLUMN IF EXISTS auto_update_frequency,
    DROP COLUMN IF EXISTS update_check_frequency,
    DROP COLUMN IF EXISTS docker_registry_url,
    DROP COLUMN IF EXISTS smtp_enabled,
    DROP COLUMN IF EXISTS smtp_from_name,
    DROP COLUMN IF EXISTS smtp_from_address,
    DROP COLUMN IF EXISTS smtp_host,
    DROP COLUMN IF EXISTS smtp_port,
    DROP COLUMN IF EXISTS smtp_encryption,
    DROP COLUMN IF EXISTS smtp_username_enc,
    DROP COLUMN IF EXISTS smtp_password_enc,
    DROP COLUMN IF EXISTS smtp_timeout,
    DROP COLUMN IF EXISTS resend_enabled,
    DROP COLUMN IF EXISTS resend_api_key_enc;
