package proxy

import (
	"encoding/base64"
	"fmt"
	"net"
	"strings"

	"github.com/dockfin/dockfin/internal/sshx"
	"golang.org/x/crypto/ssh"
)

const panelDynamicPath = "/data/dockfin/proxy/traefik/dynamic/panel.yml"

// SyncPanelRoute writes Traefik file-provider config so the instance public URL
// (Settings → Domain) reaches the Dockfin panel on :8000. Empty publicURL removes the route.
func SyncPanelRoute(client *ssh.Client, publicURL, panelServiceURL string) error {
	if client == nil {
		return fmt.Errorf("ssh client required")
	}
	if panelServiceURL == "" {
		panelServiceURL = "http://dockfin:8000"
	}
	host := sanitizePanelHost(PrimaryHost(publicURL))
	if host == "" || host == "localhost" || host == "127.0.0.1" || IsMagicDomainHost(host) || net.ParseIP(host) != nil {
		_, _, _ = sshx.Run(client, "rm -f "+panelDynamicPath)
		return nil
	}

	body := buildPanelDynamicYAML(host, panelServiceURL, WantAutoHTTPS(publicURL))

	if ProxyStatus(client) != "running" {
		return fmt.Errorf("proxy not running — validate the server first")
	}
	if err := ensureTraefikFileProvider(client); err != nil {
		return err
	}
	if err := ensurePanelOnProxyNetwork(client); err != nil {
		return err
	}
	_, _, _ = sshx.Run(client, "mkdir -p /data/dockfin/proxy/traefik/dynamic")
	b64 := base64.StdEncoding.EncodeToString([]byte(body))
	cmd := fmt.Sprintf("echo '%s' | base64 -d > %s", b64, panelDynamicPath)
	_, errOut, err := sshx.Run(client, cmd)
	if err != nil {
		return fmt.Errorf("write panel route: %v %s", err, errOut)
	}
	return nil
}

// sanitizePanelHost keeps Traefik Host(`…`) safe (no backticks / spaces).
func sanitizePanelHost(host string) string {
	host = strings.ToLower(strings.TrimSpace(host))
	var b strings.Builder
	for _, r := range host {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '.', r == '-':
			b.WriteRune(r)
		}
	}
	return b.String()
}

func buildPanelDynamicYAML(host, panelServiceURL string, wantTLS bool) string {
	var body strings.Builder
	body.WriteString("# Generated by Dockfin — instance panel route\n")
	body.WriteString("http:\n")
	body.WriteString("  routers:\n")
	if wantTLS {
		body.WriteString("    dockfin-panel:\n")
		body.WriteString("      rule: Host(`" + host + "`)\n")
		body.WriteString("      entryPoints:\n")
		body.WriteString("        - https\n")
		body.WriteString("      service: dockfin-panel\n")
		body.WriteString("      tls:\n")
		body.WriteString("        certResolver: letsencrypt\n")
		body.WriteString("    dockfin-panel-http:\n")
		body.WriteString("      rule: Host(`" + host + "`)\n")
		body.WriteString("      entryPoints:\n")
		body.WriteString("        - http\n")
		body.WriteString("      middlewares:\n")
		body.WriteString("        - dockfin-panel-redirect\n")
		body.WriteString("      service: dockfin-panel\n")
		body.WriteString("  middlewares:\n")
		body.WriteString("    dockfin-panel-redirect:\n")
		body.WriteString("      redirectScheme:\n")
		body.WriteString("        scheme: https\n")
		body.WriteString("        permanent: true\n")
	} else {
		body.WriteString("    dockfin-panel:\n")
		body.WriteString("      rule: Host(`" + host + "`)\n")
		body.WriteString("      entryPoints:\n")
		body.WriteString("        - http\n")
		body.WriteString("      service: dockfin-panel\n")
	}
	body.WriteString("  services:\n")
	body.WriteString("    dockfin-panel:\n")
	body.WriteString("      loadBalancer:\n")
	body.WriteString("        servers:\n")
	body.WriteString("          - url: " + panelServiceURL + "\n")
	return body.String()
}

func ensureTraefikFileProvider(client *ssh.Client) error {
	out, _, err := sshx.RunArgs(client, "docker", "inspect", "-f",
		`{{range .Mounts}}{{.Destination}} {{end}}`, TraefikContainer)
	if err == nil && strings.Contains(out, "/dynamic") {
		return nil
	}
	return StartTraefik(client, "", "dockfin", "")
}

// ensurePanelOnProxyNetwork attaches the compose Dockfin container to the proxy
// network with alias "dockfin" so Traefik can reach http://dockfin:8000.
func ensurePanelOnProxyNetwork(client *ssh.Client) error {
	idOut, _, err := sshx.Run(client, `docker ps -qf 'label=com.docker.compose.service=dockfin' | head -1`)
	id := strings.TrimSpace(idOut)
	if err != nil || id == "" {
		idOut, _, _ = sshx.Run(client, `docker ps -qf 'name=dockfin-dockfin' | head -1`)
		id = strings.TrimSpace(idOut)
	}
	if id == "" {
		return fmt.Errorf("dockfin panel container not found on host")
	}

	aliasOut, _, _ := sshx.Run(client, fmt.Sprintf(
		`docker inspect -f '{{range $k,$v := .NetworkSettings.Networks}}{{if eq $k "dockfin"}}{{range $v.Aliases}}{{.}} {{end}}{{end}}{{end}}' %s`,
		id,
	))
	hasAlias := strings.Contains(" "+aliasOut+" ", " dockfin ")

	if !hasAlias {
		// Already on network without alias — reconnect so Traefik DNS name works.
		_, _, _ = sshx.RunArgs(client, "docker", "network", "disconnect", "dockfin", id)
		_, errOut, connErr := sshx.RunArgs(client, "docker", "network", "connect", "--alias", "dockfin", "dockfin", id)
		if connErr != nil {
			return fmt.Errorf("network connect: %v %s", connErr, errOut)
		}
		return nil
	}

	_, errOut, connErr := sshx.RunArgs(client, "docker", "network", "connect", "--alias", "dockfin", "dockfin", id)
	if connErr != nil && !strings.Contains(errOut, "already exists") && !strings.Contains(errOut, "already connected") {
		return fmt.Errorf("network connect: %v %s", connErr, errOut)
	}
	return nil
}
